### ISSUE TITLE
java.io.IOException: Cannot run program "sh": CreateProcess error=2, 系统找不到指定的文件。 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) 	at java.lang.Runtime.exec(Runtime.java:621) 	at java.lang.Runtime.exec(Runtime.java:451) 	at java.lang.Runtime.exec(Runtime.java:348) 	at shellService.ServiceShellUtils.execCommand(ServiceShellUtils.java:58) 	at shellService.ServiceShellUtils.execCommand(ServiceShellUtils.java:26) 	at shellService.ServiceThread$1.getText(ServiceThread.java:16) 	at shellService.Service$CreateServerThread.run(Service.java:57) Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。 	at java.lang.ProcessImpl.create(Native Method) 	at java.lang.ProcessImpl.<init>(ProcessImpl.java:444) 	at java.lang.ProcessImpl.start(ProcessImpl.java:139) 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) 	... 7 more

### ISSUE THREAD

**Issue by LPLuck** [gtf35/app_process-shell-use#10]
java.io.IOException: Cannot run program "sh": CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:621)
	at java.lang.Runtime.exec(Runtime.java:451)
	at java.lang.Runtime.exec(Runtime.java:348)
	at shellService.ServiceShellUtils.execCommand(ServiceShellUtils.java:58)
	at shellService.ServiceShellUtils.execCommand(ServiceShellUtils.java:26)
	at shellService.ServiceThread$1.getText(ServiceThread.java:16)
	at shellService.Service$CreateServerThread.run(Service.java:57)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:444)
	at java.lang.ProcessImpl.start(ProcessImpl.java:139)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 7 more

**Comment by gtf35** [comment]
很抱歉刚回复（晚的有点离谱），应该是手机定制上的问题
